### ISSUE TITLE
partitionType is 110    and    FAT32

### ISSUE THREAD

**Issue by XIONG-WEN** [magnusja/libaums#103]
![qq 20170810195114](https://user-images.githubusercontent.com/2231676/29169222-6f8542e8-7e05-11e7-9e8e-e78450f0a368.png)

**Comment by magnusja** [comment]
Which version are you using and what partition type should it be?

**Comment by magnusja** [comment]
Oh sorry, just saw that it should be FAT32. Are you using develop branch or 0.5.5?

**Comment by XIONG-WEN** [comment]
Thank you for reply.
I am using 0.5.5.
I set type = 2 when partitionType == 116 .
![1](https://user-images.githubusercontent.com/2231676/29209826-2011d852-7ec3-11e7-8121-ee9b1143d3c0.png)
![2](https://user-images.githubusercontent.com/2231676/29209827-2027d274-7ec3-11e7-8dd9-490699aa673c.png)


I will get usb files.

**Comment by XIONG-WEN** [comment]
@magnusja 
Hi, I have a problem to need your help.
I have an fat32 USB drive, but the partitionType is 116. In your codes can not mapping out 'fat32', so it doesn't work.

**Comment by magnusja** [comment]
Hey there,

so 110 in hex is 0x6E and 116 in hex is 0x74. If you have a look on Wikipedia (https://en.wikipedia.org/wiki/Partition_type) and look up these values you can see that they are not usually referring to FAT32.

I would suggest to reformat it and see if it works after that.
What you also can try is to use the current develop branch, I fixed a bug while reading the partition type, but I doubt that this bug is affecting you. 

Where did you get this drive? Is there something special about it? 

Another source: https://www.win.tue.nl/~aeb/partitions/partition_types-1.html

**Comment by XIONG-WEN** [comment]
Thank you!
The new version is no problem.
